series: Intermediate C++
title: Operator Overloading
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Operator overloads are a cool alternative for functions when function calling syntax is awkward to use.
language: C++
tags:
  - Core
extra_resources:
  - link: http://stackoverflow.com/questions/4421706/operator-overloading/4421715#4421715
    title: A huge stack overflow page about operator overloading, when and how to do it.
connections:
  - series: Intermediate C++
    title: Bitwise Operators
  - series: Basic C++
    title: Overloading
  - series: Basic C++
    title: C++ Console IO